name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  its-not-my-name:
    strategy:
      matrix:
        version: [ 18 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Restore cached node modules
        id: cache-npm
        uses: actions/cache/restore@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-${{ node-version }}
      - run: npm ci
      - name: Cache node modules
        id: cache-npm
        uses: actions/save/restore@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-${{ node-version }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sibiraj-s/action-eslint@v2
        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
  build:
    needs: ["its-not-my-name", "lint"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Restore cached node modules
        id: cache-npm
        uses: actions/cache/restore@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-${{ node-version }}
      - run: npm ci #why?
      - run: npm run build

